AWSTemplateFormatVersion: "2010-09-09"
Description: "Plantilla para crear EC2 y grupo de seguridad"
Parameters:
  EC2InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
  EC2_OS:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/canonical/ubuntu/server/20.04/stable/current/amd64/hvm/ebs-gp2/ami-id
Resources:
  AplicationServerSecurityGroup2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Grupo de seguridad creado desde la plantilla"
      GroupName: AppServerSecurityGroup2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
  TomcatEC2:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType:
        - Ref: EC2InstanceType
      ImageId:
        - Ref: EC2_OS
      IamInstanceProfile: "LabInstanceProfile"
      KeyName: "vockey"
      Tags:
        - Key: "Name"
          Value: "TomcatEC2_2"
      SecurityGroupIds:
        - Ref: AplicationServerSecurityGroup2
